modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://github.com/danny8208/explosiverings/issues" #optional
[[mods]] #mandatory
modId="explosiverings" #mandatory
version="${1.0}" #mandatory
displayName="ExplosiveRings" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="http://github.com/Danny8208" #optional
#logoFile="hungerrings.png" #optional
#credits="some Calculator and gobber2 code" #optional
authors="Danny8208" #optional
description='''
A mod that adds an item that will let you eject eplosive stuff from your inventory
'''
[[dependencies.explosiverings]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.explosiverings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"